server:
  port: 8080

spring:
  application:
    name: qare-backend

  datasource:
    url: jdbc:h2:file:./qaredb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true  # optional: http://localhost:8080/h2-console

  # (Optional) logs a bit more when debugging SQL
  logging:
    level:
      org.springframework.jdbc.core.JdbcTemplate: INFO
      org.springframework.jdbc.datasource: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
